services:
  eec_sso:
    image: eec_sso:v1.0
    container_name: eec_sso
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENV=development
      - PORT=${PORT}
    networks:
      - default

networks:
  default:
    external: true
    name: eec_sso_network
