services:
  postgres:
    image: postgres:17.4-alpine3.20 # Use the PostgreSQL image
    container_name: postgres  # Name the container
    ports:
      - "5432:5432"  # Expose port 5432 for PostgreSQL
    environment:
      POSTGRES_USER: postgres # Set the default PostgreSQL user
      POSTGRES_PASSWORD: P@ssw0rd  # Set the default PostgreSQL password
      POSTGRES_DB: keycloak_db # Set the default PostgreSQL database
    restart: unless-stopped  # Restart the container unless stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data  # Use a named volume for PostgreSQL data
    networks:
      - default # Connect the container to the keycloak-net network

networks:
  default:
    external: true
    name: sso-net
