
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: P@ssw0rd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - default
    command: start-dev
networks:
  default:
    external: true
    name: sso-net