services:
  eec_sso:
    image: eec_sso:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eec_sso
    ports:
      - "3089:3089"
    environment:
      - ENV=development
      - DB_HOST=postgres
      - PORT=3089
    networks:
      - default

networks:
  default:
    external: true
    name: sso-net
